### ISSUE TITLE
[BUG, critical] after update (lilycalInventory 1.1.0 --> 1.3.1) ALL Modular Avatar Menu additions are gone

### ISSUE THREAD

**Issue by Martin-H2** [lilxyzw/lilycalInventory#126] opened 2024-09-25 22:59 UTC
Updated lilycalInventory 1.1.0 --> 1.3.1 in all projects

All menu additions added by "Modular avatar" with: MA menu installer + menu group + menu item(s) broke and and no longer added to the avatar menu. (no other changes done other than updating lilycalInventory).
This happend on all my projects after updating.

This also renders all projects broken, because you can not go back to 1.1.0 (or any version below 1.3), or otherwise you get this message in VCC:
![image](https://github.com/user-attachments/assets/1aaf90fb-802b-4153-ac6c-8e2b0bf2f7ac)

EDIT: also no error messages in the console. just an empty menu
EDIT: I temporary fixed my projects, by getting "lilycalInventory 1.1.0" from a friend and editing the vpm-manifest.json to accept this version (at 2 places)

**Comment by lilxyzw** [comment] 2024-09-26 10:44
Probably a duplicate of #120

**Comment by lilxyzw** [comment] 2024-09-28 08:51
It is a bug in VCC that you cannot downgrade packages. lilycalInventory 1.1.0 supports Unity 2022. I recommend creating an issue in vcc.

Repository: https://github.com/vrchat-community/creator-companion/issues
Related issue: https://github.com/vrchat-community/creator-companion/issues/367

**Closed** 2024-09-28 14:14 UTC
Labels: duplicate
